# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-18.04"
# BOX_VERSION = "201803.24.0"

Vagrant.configure("2") do |config|

  config.vm.provider "hyperv" do |v|
    v.enable_virtualization_extensions = true
    v.linked_clone = true
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "monitor" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    # subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.provider "hyperv" do |hv|
      hv.memory = 4096
    end
    subconfig.vm.hostname = "monitor"
    subconfig.vm.network "public_network", bridge: "Intel(R) I350 Gigabit Network Connection #3 - Virtual Switch"
    subconfig.vm.provision "file", source: "scripts/.", destination: "/home/vagrant/scripts"
    subconfig.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive && \
      apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && \
      add-apt-repository "deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.liquidtelecom.com/repo/10.4/ubuntu $(lsb_release -cs) main" && \
      apt-get -y update && apt-get -y -o Dpkg::Options::="--force-confnew" upgrade && apt-get -y autoremove && \
      apt-get -y install php php-{xml,cli,opcache,gd,intl,readline,mysql,curl,mbstring,ldap,json} \
                         apache2 libapache2-mod-php mariadb-server mariadb-client icinga2 icingaweb2 icinga2-ido-mysql && \
      mysql -uroot -pPASS < /home/vagrant/scripts/icinga2_db.sql && \
      mysql -uroot -pPASS < /home/vagrant/scripts/icinga2web_db.sql && \
      icinga2 feature enable command  ido-mysql && systemctl restart icinga2.service && \
      mysql -uroot icinga2_db -pPASS < /usr/share/icinga2-ido-mysql/schema/mysql.sql
    SHELL
  end

end
