version: '2'
services:
  proxy:
    image: dcassiero/nginx-proxy:1.2
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: proxy=true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
